-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        no_warps = true,
    },
    decoration = {
        blur = {
            size = 4,
        },
        dim_strength = 0.15,
    },
})

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "-1920x10",
    scale = 1,
    cm = "srgb",
})
